---
title: "Lab 07 - University of Edinburgh Art Collection"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
library(stringr)
library(robotstxt)
```


```{r load-data, message = FALSE}
# Remove eval = FALSE or set it to TRUE once data is ready to be loaded
uoe_art <- read_csv("data/uoe-art.csv")
```

### Exercise 9

```{r separate-title-date, error = TRUE}
uoe_art <- uoe_art %>%
  separate(title, into = c("title", "date"), sep = "\\(") %>%
  mutate(year = str_remove(date, "\\)") %>% as.numeric()) %>%
  select(title, artist, year, link)
```

### Exercise 11
```{r, error=FALSE}

skim(uoe_art)
sum(is.na(uoe_art$artist))
sum(is.na(uoe_art$title))
sum(is.na(uoe_art$year))
sum(is.na(uoe_art$link))
```
### Exercise 11,12

```{r}

summary(uoe_art$year)
## some weird thing is in there (2), but let's skip it 



ggplot(data = uoe_art, aes(x = year)) +
  geom_histogram()+
  coord_cartesian(xlim = c(1700, 2030))
  

```

## ex 13, 14 15

```{r}
uoe_art %>%
  filter(year==2)%>%
  View()

uoe_art %>%
  filter(year==2)%>%
  View()


uoe_art$year<-ifelse(uoe_art$year==2,1964,uoe_art$year)

uoe_art$title[uoe_art$title=="Death Mask"] <- "Death Mask (2)"



ggplot(data = uoe_art, aes(x = year)) +
  geom_histogram()



uoe_art %>%
  count(artist) %>%
  arrange(desc(n))

uoe_art %>% 
  filter(str_detect(title, fixed('child', ignore_case = TRUE))) 

    
```

